{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cecabb9b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "import random\n",
    "import string"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "c5d7dda0",
   "metadata": {},
   "outputs": [],
   "source": [
    "class SimpleisticTest(unittest.TestCase):\n",
    "    def test1(self):\n",
    "        a = random.choice(string.ascii_letters)\n",
    "        b = random.choice(string.ascii_letters)\n",
    "        self.assertEqual(a, b)\n",
    "\n",
    "    def test2(self):\n",
    "        a = random.choice(string.ascii_letters)\n",
    "        b = random.choice(string.ascii_letters)\n",
    "        self.assertNotEqual(a, b)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "5e4fb44b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "test1 (__main__.SimpleisticTest.test1) ... FAIL\n",
      "test2 (__main__.SimpleisticTest.test2) ... ok\n",
      "\n",
      "======================================================================\n",
      "FAIL: test1 (__main__.SimpleisticTest.test1)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3986460911.py\", line 5, in test1\n",
      "    self.assertEqual(a, b)\n",
      "AssertionError: 'l' != 'y'\n",
      "- l\n",
      "+ y\n",
      "\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 2 tests in 0.004s\n",
      "\n",
      "FAILED (failures=1)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24de04e77d0>"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d3411e0b",
   "metadata": {},
   "outputs": [],
   "source": [
    "class OutcomesTest(unittest.TestCase):\n",
    "    def testPass(self):\n",
    "        return\n",
    "    def testFail(self):\n",
    "        self.assertFalse(True)\n",
    "    def testError(self):\n",
    "        raise RuntimeError('Test error!')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "6ba16c25",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "testError (__main__.OutcomesTest.testError) ... ERROR\n",
      "testFail (__main__.OutcomesTest.testFail) ... FAIL\n",
      "testPass (__main__.OutcomesTest.testPass) ... ok\n",
      "test1 (__main__.SimpleisticTest.test1) ... FAIL\n",
      "test2 (__main__.SimpleisticTest.test2) ... ok\n",
      "\n",
      "======================================================================\n",
      "ERROR: testError (__main__.OutcomesTest.testError)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 7, in testError\n",
      "    raise RuntimeError('Test error!')\n",
      "RuntimeError: Test error!\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.OutcomesTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 5, in testFail\n",
      "    self.assertFalse(True)\n",
      "AssertionError: True is not false\n",
      "\n",
      "======================================================================\n",
      "FAIL: test1 (__main__.SimpleisticTest.test1)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3986460911.py\", line 5, in test1\n",
      "    self.assertEqual(a, b)\n",
      "AssertionError: 'H' != 'A'\n",
      "- H\n",
      "+ A\n",
      "\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 5 tests in 0.011s\n",
      "\n",
      "FAILED (failures=2, errors=1)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24de051a7e0>"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "083e3bb2",
   "metadata": {},
   "outputs": [],
   "source": [
    "class FailureMessageTest(unittest.TestCase):\n",
    "    def testFail(self):\n",
    "        self.assertFalse(True, 'Сообщение о ошибке')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "db569a89",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "testFail (__main__.FailureMessageTest.testFail) ... FAIL\n",
      "testError (__main__.OutcomesTest.testError) ... ERROR\n",
      "testFail (__main__.OutcomesTest.testFail) ... FAIL\n",
      "testPass (__main__.OutcomesTest.testPass) ... ok\n",
      "test1 (__main__.SimpleisticTest.test1) ... FAIL\n",
      "test2 (__main__.SimpleisticTest.test2) ... ok\n",
      "\n",
      "======================================================================\n",
      "ERROR: testError (__main__.OutcomesTest.testError)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 7, in testError\n",
      "    raise RuntimeError('Test error!')\n",
      "RuntimeError: Test error!\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.FailureMessageTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3323480498.py\", line 3, in testFail\n",
      "    self.assertFalse(True, 'Сообщение о ошибке')\n",
      "AssertionError: True is not false : Сообщение о ошибке\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.OutcomesTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 5, in testFail\n",
      "    self.assertFalse(True)\n",
      "AssertionError: True is not false\n",
      "\n",
      "======================================================================\n",
      "FAIL: test1 (__main__.SimpleisticTest.test1)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3986460911.py\", line 5, in test1\n",
      "    self.assertEqual(a, b)\n",
      "AssertionError: 's' != 'Y'\n",
      "- s\n",
      "+ Y\n",
      "\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 6 tests in 0.010s\n",
      "\n",
      "FAILED (failures=3, errors=1)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24de0531730>"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "5a53f0a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "class TruthTest(unittest.TestCase):\n",
    "    def testAssertTrue(self):\n",
    "        self.assertTrue(True)\n",
    "    def testAssertFalse(self):\n",
    "        self.assertFalse(False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "90fcd2f3",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "testFail (__main__.FailureMessageTest.testFail) ... FAIL\n",
      "testError (__main__.OutcomesTest.testError) ... ERROR\n",
      "testFail (__main__.OutcomesTest.testFail) ... FAIL\n",
      "testPass (__main__.OutcomesTest.testPass) ... ok\n",
      "test1 (__main__.SimpleisticTest.test1) ... FAIL\n",
      "test2 (__main__.SimpleisticTest.test2) ... ok\n",
      "testAssertFalse (__main__.TruthTest.testAssertFalse) ... ok\n",
      "testAssertTrue (__main__.TruthTest.testAssertTrue) ... ok\n",
      "\n",
      "======================================================================\n",
      "ERROR: testError (__main__.OutcomesTest.testError)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 7, in testError\n",
      "    raise RuntimeError('Test error!')\n",
      "RuntimeError: Test error!\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.FailureMessageTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3323480498.py\", line 3, in testFail\n",
      "    self.assertFalse(True, 'Сообщение о ошибке')\n",
      "AssertionError: True is not false : Сообщение о ошибке\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.OutcomesTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 5, in testFail\n",
      "    self.assertFalse(True)\n",
      "AssertionError: True is not false\n",
      "\n",
      "======================================================================\n",
      "FAIL: test1 (__main__.SimpleisticTest.test1)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3986460911.py\", line 5, in test1\n",
      "    self.assertEqual(a, b)\n",
      "AssertionError: 'Q' != 'q'\n",
      "- Q\n",
      "+ q\n",
      "\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 8 tests in 0.017s\n",
      "\n",
      "FAILED (failures=3, errors=1)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24de04e6c30>"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "6b49f2d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "class EqualityTest(unittest.TestCase):\n",
    "    def testExpectEqual(self):\n",
    "        self.assertEqual(1, 3 - 2)\n",
    "    def testExpectEqualFails(self):\n",
    "        self.assertEqual(2, 3 - 2)\n",
    "    def testExpectNotEqual(self):\n",
    "        self.assertNotEqual(2, 3 - 2)\n",
    "    def testExpectNotEqualFails(self):\n",
    "        self.assertNotEqual(1, 3 - 2)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "336cb6c4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "testExpectEqual (__main__.EqualityTest.testExpectEqual) ... ok\n",
      "testExpectEqualFails (__main__.EqualityTest.testExpectEqualFails) ... FAIL\n",
      "testExpectNotEqual (__main__.EqualityTest.testExpectNotEqual) ... ok\n",
      "testExpectNotEqualFails (__main__.EqualityTest.testExpectNotEqualFails) ... FAIL\n",
      "testFail (__main__.FailureMessageTest.testFail) ... FAIL\n",
      "testError (__main__.OutcomesTest.testError) ... ERROR\n",
      "testFail (__main__.OutcomesTest.testFail) ... FAIL\n",
      "testPass (__main__.OutcomesTest.testPass) ... ok\n",
      "test1 (__main__.SimpleisticTest.test1) ... FAIL\n",
      "test2 (__main__.SimpleisticTest.test2) ... ok\n",
      "testAssertFalse (__main__.TruthTest.testAssertFalse) ... ok\n",
      "testAssertTrue (__main__.TruthTest.testAssertTrue) ... ok\n",
      "\n",
      "======================================================================\n",
      "ERROR: testError (__main__.OutcomesTest.testError)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 7, in testError\n",
      "    raise RuntimeError('Test error!')\n",
      "RuntimeError: Test error!\n",
      "\n",
      "======================================================================\n",
      "FAIL: testExpectEqualFails (__main__.EqualityTest.testExpectEqualFails)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\2283161862.py\", line 7, in testExpectEqualFails\n",
      "    self.assertEqual(2, 3 - 2)\n",
      "AssertionError: 2 != 1\n",
      "\n",
      "======================================================================\n",
      "FAIL: testExpectNotEqualFails (__main__.EqualityTest.testExpectNotEqualFails)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\2283161862.py\", line 11, in testExpectNotEqualFails\n",
      "    self.assertNotEqual(1, 3 - 2)\n",
      "AssertionError: 1 == 1\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.FailureMessageTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3323480498.py\", line 3, in testFail\n",
      "    self.assertFalse(True, 'Сообщение о ошибке')\n",
      "AssertionError: True is not false : Сообщение о ошибке\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.OutcomesTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 5, in testFail\n",
      "    self.assertFalse(True)\n",
      "AssertionError: True is not false\n",
      "\n",
      "======================================================================\n",
      "FAIL: test1 (__main__.SimpleisticTest.test1)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3986460911.py\", line 5, in test1\n",
      "    self.assertEqual(a, b)\n",
      "AssertionError: 'R' != 'p'\n",
      "- R\n",
      "+ p\n",
      "\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 12 tests in 0.024s\n",
      "\n",
      "FAILED (failures=5, errors=1)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24de04e4d70>"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "e3a62b76",
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "class AlmostEqualTest(unittest.TestCase):\n",
    "    def testEqual(self):\n",
    "        self.assertEqual(1.1, 3.3 - 2.2)\n",
    "    def testAlmostEqual(self):\n",
    "        self.assertAlmostEqual(1.1, 3.3 - 2.2, places=1)\n",
    "    def testNotAlmostEqual(self):\n",
    "        self.assertNotAlmostEqual(1.1, 3.3 - 2.0, places=1)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "677ed808",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "testAlmostEqual (__main__.AlmostEqualTest.testAlmostEqual) ... ok\n",
      "testEqual (__main__.AlmostEqualTest.testEqual) ... FAIL\n",
      "testNotAlmostEqual (__main__.AlmostEqualTest.testNotAlmostEqual) ... ok\n",
      "testExpectEqual (__main__.EqualityTest.testExpectEqual) ... ok\n",
      "testExpectEqualFails (__main__.EqualityTest.testExpectEqualFails) ... FAIL\n",
      "testExpectNotEqual (__main__.EqualityTest.testExpectNotEqual) ... ok\n",
      "testExpectNotEqualFails (__main__.EqualityTest.testExpectNotEqualFails) ... FAIL\n",
      "testFail (__main__.FailureMessageTest.testFail) ... FAIL\n",
      "testError (__main__.OutcomesTest.testError) ... ERROR\n",
      "testFail (__main__.OutcomesTest.testFail) ... FAIL\n",
      "testPass (__main__.OutcomesTest.testPass) ... ok\n",
      "test1 (__main__.SimpleisticTest.test1) ... FAIL\n",
      "test2 (__main__.SimpleisticTest.test2) ... ok\n",
      "testAssertFalse (__main__.TruthTest.testAssertFalse) ... ok\n",
      "testAssertTrue (__main__.TruthTest.testAssertTrue) ... ok\n",
      "\n",
      "======================================================================\n",
      "ERROR: testError (__main__.OutcomesTest.testError)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 7, in testError\n",
      "    raise RuntimeError('Test error!')\n",
      "RuntimeError: Test error!\n",
      "\n",
      "======================================================================\n",
      "FAIL: testEqual (__main__.AlmostEqualTest.testEqual)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\1691792061.py\", line 5, in testEqual\n",
      "    self.assertEqual(1.1, 3.3 - 2.2)\n",
      "AssertionError: 1.1 != 1.0999999999999996\n",
      "\n",
      "======================================================================\n",
      "FAIL: testExpectEqualFails (__main__.EqualityTest.testExpectEqualFails)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\2283161862.py\", line 7, in testExpectEqualFails\n",
      "    self.assertEqual(2, 3 - 2)\n",
      "AssertionError: 2 != 1\n",
      "\n",
      "======================================================================\n",
      "FAIL: testExpectNotEqualFails (__main__.EqualityTest.testExpectNotEqualFails)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\2283161862.py\", line 11, in testExpectNotEqualFails\n",
      "    self.assertNotEqual(1, 3 - 2)\n",
      "AssertionError: 1 == 1\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.FailureMessageTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3323480498.py\", line 3, in testFail\n",
      "    self.assertFalse(True, 'Сообщение о ошибке')\n",
      "AssertionError: True is not false : Сообщение о ошибке\n",
      "\n",
      "======================================================================\n",
      "FAIL: testFail (__main__.OutcomesTest.testFail)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3554236727.py\", line 5, in testFail\n",
      "    self.assertFalse(True)\n",
      "AssertionError: True is not false\n",
      "\n",
      "======================================================================\n",
      "FAIL: test1 (__main__.SimpleisticTest.test1)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_176480\\3986460911.py\", line 5, in test1\n",
      "    self.assertEqual(a, b)\n",
      "AssertionError: 'F' != 'H'\n",
      "- F\n",
      "+ H\n",
      "\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 15 tests in 0.027s\n",
      "\n",
      "FAILED (failures=6, errors=1)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24de04e5df0>"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "74b6dec8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import textwrap\n",
    "import unittest\n",
    "\n",
    "class ContainerEqualityTest(unittest.TestCase):\n",
    "    def testCount(self):\n",
    "        self.assertCountEqual(\n",
    "        [1, 2, 3, 2],\n",
    "        [1, 3, 2, 3],\n",
    "        )\n",
    "    def testDict(self):\n",
    "        self.assertDictEqual(\n",
    "        {'a': 1, 'b': 2},\n",
    "        {'a': 1, 'b': 3},\n",
    "        )\n",
    "    def testList(self):\n",
    "        self.assertListEqual(\n",
    "        [1, 2, 3],\n",
    "        [1, 3, 2],\n",
    "        )\n",
    "    def testMultiLineString(self):\n",
    "        self.assertMultiLineEqual(\n",
    "        textwrap.dedent(\"\"\"\n",
    "        Это\n",
    "        первая\n",
    "        строка\n",
    "        \"\"\"),\n",
    "        textwrap.dedent(\"\"\"\n",
    "        Это\n",
    "        вторая\n",
    "        строка\n",
    "        \"\"\")\n",
    "        )\n",
    "    def testSequence(self):\n",
    "        self.assertSequenceEqual(\n",
    "        [1, 2, 3],\n",
    "        [1, 3, 2],\n",
    "        )\n",
    "    def testSet(self) :\n",
    "        self.assertSetEqual(\n",
    "        set([1, 2, 3]),\n",
    "        set([1, 3, 2, 4]),\n",
    "        )\n",
    "    def testTuple(self):\n",
    "        self.assertTupleEqual(\n",
    "        (1, 'a'),\n",
    "        (1, 'b'),\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "79966f2c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: testCount (__main__.ContainerEqualityTest.testCount)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 6, in testCount\n",
      "    self.assertCountEqual(\n",
      "AssertionError: Element counts were not equal:\n",
      "First has 2, Second has 1:  2\n",
      "First has 1, Second has 2:  3\n",
      "\n",
      "======================================================================\n",
      "FAIL: testDict (__main__.ContainerEqualityTest.testDict)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 11, in testDict\n",
      "    self.assertDictEqual(\n",
      "AssertionError: {'a': 1, 'b': 2} != {'a': 1, 'b': 3}\n",
      "- {'a': 1, 'b': 2}\n",
      "?               ^\n",
      "\n",
      "+ {'a': 1, 'b': 3}\n",
      "?               ^\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testList (__main__.ContainerEqualityTest.testList)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 16, in testList\n",
      "    self.assertListEqual(\n",
      "AssertionError: Lists differ: [1, 2, 3] != [1, 3, 2]\n",
      "\n",
      "First differing element 1:\n",
      "2\n",
      "3\n",
      "\n",
      "- [1, 2, 3]\n",
      "+ [1, 3, 2]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testMultiLineString (__main__.ContainerEqualityTest.testMultiLineString)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 21, in testMultiLineString\n",
      "    self.assertMultiLineEqual(\n",
      "AssertionError: '\\nЭто\\nпервая\\nстрока\\n' != '\\nЭто\\nвторая\\nстрока\\n'\n",
      "  \n",
      "  Это\n",
      "- первая\n",
      "+ вторая\n",
      "  строка\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSequence (__main__.ContainerEqualityTest.testSequence)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 34, in testSequence\n",
      "    self.assertSequenceEqual(\n",
      "AssertionError: Sequences differ: [1, 2, 3] != [1, 3, 2]\n",
      "\n",
      "First differing element 1:\n",
      "2\n",
      "3\n",
      "\n",
      "- [1, 2, 3]\n",
      "+ [1, 3, 2]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSet (__main__.ContainerEqualityTest.testSet)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 39, in testSet\n",
      "    self.assertSetEqual(\n",
      "AssertionError: Items in the second set but not the first:\n",
      "4\n",
      "\n",
      "======================================================================\n",
      "FAIL: testTuple (__main__.ContainerEqualityTest.testTuple)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 44, in testTuple\n",
      "    self.assertTupleEqual(\n",
      "AssertionError: Tuples differ: (1, 'a') != (1, 'b')\n",
      "\n",
      "First differing element 1:\n",
      "'a'\n",
      "'b'\n",
      "\n",
      "- (1, 'a')\n",
      "?      ^\n",
      "\n",
      "+ (1, 'b')\n",
      "?      ^\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testDict (__main__.ContainerMembershipTest.testDict)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\3879194459.py\", line 5, in testDict\n",
      "    self.assertIn(4, {1: 'a', 2: 'b', 3: 'c'})\n",
      "AssertionError: 4 not found in {1: 'a', 2: 'b', 3: 'c'}\n",
      "\n",
      "======================================================================\n",
      "FAIL: testList (__main__.ContainerMembershipTest.testList)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\3879194459.py\", line 7, in testList\n",
      "    self.assertIn(4, [1, 2, 3])\n",
      "AssertionError: 4 not found in [1, 2, 3]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSet (__main__.ContainerMembershipTest.testSet)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\3879194459.py\", line 9, in testSet\n",
      "    self.assertIn(4, set([1, 2, 3]))\n",
      "AssertionError: 4 not found in {1, 2, 3}\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 10 tests in 0.010s\n",
      "\n",
      "FAILED (failures=10)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24f84ca51c0>"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=1, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "a16e693f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "class ContainerMembershipTest(unittest.TestCase):\n",
    "    def testDict(self):\n",
    "        self.assertIn(4, {1: 'a', 2: 'b', 3: 'c',4: 'z'})\n",
    "    def testList(self):\n",
    "        self.assertIn(4, [1, 2, 3])\n",
    "    def testSet(self):\n",
    "        self.assertIn(4, set([1, 2, 3]))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "334572ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFF.FF\n",
      "======================================================================\n",
      "FAIL: testCount (__main__.ContainerEqualityTest.testCount)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 6, in testCount\n",
      "    self.assertCountEqual(\n",
      "AssertionError: Element counts were not equal:\n",
      "First has 2, Second has 1:  2\n",
      "First has 1, Second has 2:  3\n",
      "\n",
      "======================================================================\n",
      "FAIL: testDict (__main__.ContainerEqualityTest.testDict)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 11, in testDict\n",
      "    self.assertDictEqual(\n",
      "AssertionError: {'a': 1, 'b': 2} != {'a': 1, 'b': 3}\n",
      "- {'a': 1, 'b': 2}\n",
      "?               ^\n",
      "\n",
      "+ {'a': 1, 'b': 3}\n",
      "?               ^\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testList (__main__.ContainerEqualityTest.testList)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 16, in testList\n",
      "    self.assertListEqual(\n",
      "AssertionError: Lists differ: [1, 2, 3] != [1, 3, 2]\n",
      "\n",
      "First differing element 1:\n",
      "2\n",
      "3\n",
      "\n",
      "- [1, 2, 3]\n",
      "+ [1, 3, 2]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testMultiLineString (__main__.ContainerEqualityTest.testMultiLineString)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 21, in testMultiLineString\n",
      "    self.assertMultiLineEqual(\n",
      "AssertionError: '\\nЭто\\nпервая\\nстрока\\n' != '\\nЭто\\nвторая\\nстрока\\n'\n",
      "  \n",
      "  Это\n",
      "- первая\n",
      "+ вторая\n",
      "  строка\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSequence (__main__.ContainerEqualityTest.testSequence)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 34, in testSequence\n",
      "    self.assertSequenceEqual(\n",
      "AssertionError: Sequences differ: [1, 2, 3] != [1, 3, 2]\n",
      "\n",
      "First differing element 1:\n",
      "2\n",
      "3\n",
      "\n",
      "- [1, 2, 3]\n",
      "+ [1, 3, 2]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSet (__main__.ContainerEqualityTest.testSet)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 39, in testSet\n",
      "    self.assertSetEqual(\n",
      "AssertionError: Items in the second set but not the first:\n",
      "4\n",
      "\n",
      "======================================================================\n",
      "FAIL: testTuple (__main__.ContainerEqualityTest.testTuple)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 44, in testTuple\n",
      "    self.assertTupleEqual(\n",
      "AssertionError: Tuples differ: (1, 'a') != (1, 'b')\n",
      "\n",
      "First differing element 1:\n",
      "'a'\n",
      "'b'\n",
      "\n",
      "- (1, 'a')\n",
      "?      ^\n",
      "\n",
      "+ (1, 'b')\n",
      "?      ^\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testList (__main__.ContainerMembershipTest.testList)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\524951416.py\", line 7, in testList\n",
      "    self.assertIn(4, [1, 2, 3])\n",
      "AssertionError: 4 not found in [1, 2, 3]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSet (__main__.ContainerMembershipTest.testSet)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\524951416.py\", line 9, in testSet\n",
      "    self.assertIn(4, set([1, 2, 3]))\n",
      "AssertionError: 4 not found in {1, 2, 3}\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 10 tests in 0.011s\n",
      "\n",
      "FAILED (failures=9)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24f88f36c30>"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=1, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6dbac664",
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "def raises_error(*args, **kwds):\n",
    "    raise ValueError('Invalid value: ' + str(args) + str(kwds))\n",
    "    \n",
    "    \n",
    "class ExceptionTest(unittest.TestCase):\n",
    "    def testTrapLocally(self):\n",
    "        try:\n",
    "            raises_error('a', b='с')\n",
    "        except ValueError:\n",
    "            pass\n",
    "        else:\n",
    "            self.fail('Нет ValueError')\n",
    "    def testAssertRaises(self):\n",
    "        self.assertRaises(ValueError, raises_error, 'a', b='c')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "5fb05f27",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFF.FF..\n",
      "======================================================================\n",
      "FAIL: testCount (__main__.ContainerEqualityTest.testCount)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 6, in testCount\n",
      "    self.assertCountEqual(\n",
      "AssertionError: Element counts were not equal:\n",
      "First has 2, Second has 1:  2\n",
      "First has 1, Second has 2:  3\n",
      "\n",
      "======================================================================\n",
      "FAIL: testDict (__main__.ContainerEqualityTest.testDict)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 11, in testDict\n",
      "    self.assertDictEqual(\n",
      "AssertionError: {'a': 1, 'b': 2} != {'a': 1, 'b': 3}\n",
      "- {'a': 1, 'b': 2}\n",
      "?               ^\n",
      "\n",
      "+ {'a': 1, 'b': 3}\n",
      "?               ^\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testList (__main__.ContainerEqualityTest.testList)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 16, in testList\n",
      "    self.assertListEqual(\n",
      "AssertionError: Lists differ: [1, 2, 3] != [1, 3, 2]\n",
      "\n",
      "First differing element 1:\n",
      "2\n",
      "3\n",
      "\n",
      "- [1, 2, 3]\n",
      "+ [1, 3, 2]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testMultiLineString (__main__.ContainerEqualityTest.testMultiLineString)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 21, in testMultiLineString\n",
      "    self.assertMultiLineEqual(\n",
      "AssertionError: '\\nЭто\\nпервая\\nстрока\\n' != '\\nЭто\\nвторая\\nстрока\\n'\n",
      "  \n",
      "  Это\n",
      "- первая\n",
      "+ вторая\n",
      "  строка\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSequence (__main__.ContainerEqualityTest.testSequence)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 34, in testSequence\n",
      "    self.assertSequenceEqual(\n",
      "AssertionError: Sequences differ: [1, 2, 3] != [1, 3, 2]\n",
      "\n",
      "First differing element 1:\n",
      "2\n",
      "3\n",
      "\n",
      "- [1, 2, 3]\n",
      "+ [1, 3, 2]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSet (__main__.ContainerEqualityTest.testSet)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 39, in testSet\n",
      "    self.assertSetEqual(\n",
      "AssertionError: Items in the second set but not the first:\n",
      "4\n",
      "\n",
      "======================================================================\n",
      "FAIL: testTuple (__main__.ContainerEqualityTest.testTuple)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\289919133.py\", line 44, in testTuple\n",
      "    self.assertTupleEqual(\n",
      "AssertionError: Tuples differ: (1, 'a') != (1, 'b')\n",
      "\n",
      "First differing element 1:\n",
      "'a'\n",
      "'b'\n",
      "\n",
      "- (1, 'a')\n",
      "?      ^\n",
      "\n",
      "+ (1, 'b')\n",
      "?      ^\n",
      "\n",
      "\n",
      "======================================================================\n",
      "FAIL: testList (__main__.ContainerMembershipTest.testList)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\524951416.py\", line 7, in testList\n",
      "    self.assertIn(4, [1, 2, 3])\n",
      "AssertionError: 4 not found in [1, 2, 3]\n",
      "\n",
      "======================================================================\n",
      "FAIL: testSet (__main__.ContainerMembershipTest.testSet)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_174852\\524951416.py\", line 9, in testSet\n",
      "    self.assertIn(4, set([1, 2, 3]))\n",
      "AssertionError: 4 not found in {1, 2, 3}\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 12 tests in 0.013s\n",
      "\n",
      "FAILED (failures=9)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x24f88f35760>"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=1, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4731a7b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "import unittest\n",
    "\n",
    "def setUpModule():\n",
    "    print('В setUpModule()')\n",
    "def tearDownModule():\n",
    "    print('В tearDownModule()')\n",
    "    \n",
    "class FixturesTest(unittest.TestCase):\n",
    "    @classmethod\n",
    "    def setUpClass(cls):\n",
    "        print('В setUpClass()')\n",
    "        cls.good_range = range(1, 10)\n",
    "    @classmethod\n",
    "    def tearDownClass(cls):\n",
    "        print('В tearDownClass()' )\n",
    "        del cls.good_range\n",
    "    def setUp(self):\n",
    "        super().setUp()\n",
    "        print('\\nВ setUp()')\n",
    "        self.value = random.randint(\n",
    "        self.good_range.start,\n",
    "        self.good_range.stop - 1,\n",
    "        )\n",
    "    def tearDown(self):\n",
    "        print('В tearDown()')\n",
    "        del self.value\n",
    "        super().tearDown()\n",
    "    def test1(self):\n",
    "        print('В test1()')\n",
    "        self.assertIn(self.value, self.good_range)\n",
    "    def test2(self):\n",
    "        print('В test2()')\n",
    "        self.assertIn(self.value*2, self.good_range)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "eb87535e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      ".F\n",
      "======================================================================\n",
      "FAIL: test2 (__main__.FixturesTest.test2)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_72784\\2085430996.py\", line 34, in test2\n",
      "    self.assertIn(self.value*2, self.good_range)\n",
      "AssertionError: 14 not found in range(1, 10)\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 2 tests in 0.006s\n",
      "\n",
      "FAILED (failures=1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "В setUpModule()\n",
      "В setUpClass()\n",
      "\n",
      "В setUp()\n",
      "В test1()\n",
      "В tearDown()\n",
      "\n",
      "В setUp()\n",
      "В test2()\n",
      "В tearDown()\n",
      "В tearDownClass()\n",
      "В tearDownModule()\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x1c8486bdd60>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=1, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "dcbad798",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import unittest\n",
    "\n",
    "class SkippingTest(unittest.TestCase):\n",
    "    @unittest.skip('Всегда пропущено')\n",
    "    def test(self):\n",
    "        self.assertTrue(False)\n",
    "    @unittest.skipIf(sys.version_info[0] > 2, 'Только для python 2')\n",
    "    def test_python2_only(self):\n",
    "        self.assertTrue(False)\n",
    "    @unittest.skipUnless(sys.platform == 'Darwin', 'Только для macOS')\n",
    "    def test_macos_only(self):\n",
    "        self.assertTrue(True)\n",
    "    def test__raise_skiptest(self):\n",
    "        raise unittest.SkipTest('пропуск через исключение')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3a542421",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "test1 (__main__.FixturesTest.test1) ... ok\n",
      "test2 (__main__.FixturesTest.test2) ... FAIL\n",
      "test (__main__.SkippingTest.test) ... skipped 'Всегда пропущено'\n",
      "test__raise_skiptest (__main__.SkippingTest.test__raise_skiptest) ... skipped 'пропуск через исключение'\n",
      "test_macos_only (__main__.SkippingTest.test_macos_only) ... skipped 'Только для macOS'\n",
      "test_python2_only (__main__.SkippingTest.test_python2_only) ... skipped 'Только для python 2'\n",
      "\n",
      "======================================================================\n",
      "FAIL: test2 (__main__.FixturesTest.test2)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\marina.mysh\\AppData\\Local\\Temp\\ipykernel_72784\\2085430996.py\", line 34, in test2\n",
      "    self.assertIn(self.value*2, self.good_range)\n",
      "AssertionError: 14 not found in range(1, 10)\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 6 tests in 0.012s\n",
      "\n",
      "FAILED (failures=1, skipped=4)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "В setUpModule()\n",
      "В setUpClass()\n",
      "\n",
      "В setUp()\n",
      "В test1()\n",
      "В tearDown()\n",
      "\n",
      "В setUp()\n",
      "В test2()\n",
      "В tearDown()\n",
      "В tearDownClass()\n",
      "В tearDownModule()\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x1c848987ef0>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7840bc18",
   "metadata": {},
   "outputs": [],
   "source": [
    "import unittest\n",
    "\n",
    "class Test(unittest.TestCase):\n",
    "    @unittest.expectedFailure\n",
    "    def test_never_passes(self):\n",
    "        self.assertTrue(False)\n",
    "    @unittest.expectedFailure\n",
    "    def test_always_passes(self):\n",
    "        self.assertTrue(True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1621dfe5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "test1 (__main__.FixturesTest.test1) ... ok\n",
      "test2 (__main__.FixturesTest.test2) ... ok\n",
      "test (__main__.SkippingTest.test) ... skipped 'Всегда пропущено'\n",
      "test__raise_skiptest (__main__.SkippingTest.test__raise_skiptest) ... skipped 'пропуск через исключение'\n",
      "test_macos_only (__main__.SkippingTest.test_macos_only) ... skipped 'Только для macOS'\n",
      "test_python2_only (__main__.SkippingTest.test_python2_only) ... skipped 'Только для python 2'\n",
      "test_always_passes (__main__.Test.test_always_passes) ... unexpected success\n",
      "test_never_passes (__main__.Test.test_never_passes) ... expected failure\n",
      "\n",
      "======================================================================\n",
      "UNEXPECTED SUCCESS: test_always_passes (__main__.Test.test_always_passes)\n",
      "----------------------------------------------------------------------\n",
      "Ran 8 tests in 0.013s\n",
      "\n",
      "FAILED (skipped=4, expected failures=1, unexpected successes=1)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "В setUpModule()\n",
      "В setUpClass()\n",
      "\n",
      "В setUp()\n",
      "В test1()\n",
      "В tearDown()\n",
      "\n",
      "В setUp()\n",
      "В test2()\n",
      "В tearDown()\n",
      "В tearDownClass()\n",
      "В tearDownModule()\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<unittest.main.TestProgram at 0x1c84899a420>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "unittest.main(argv=[''], verbosity=2, exit=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e867499d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
